# Generated by Django 2.2.2 on 2019-06-25 21:08

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    pass
