# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipanaro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='assigned_sex',
            field=models.IntegerField(
                blank=True,
                choices=[(1, 'Male'), (2, 'Female'), (9, 'Not Applicable')]),
        ),
    ]
