# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipanaro', '0003_auto_20160824_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
