# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipanaro', '0005_membership_drop_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='level',
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_left',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='nid_type',
            field=models.IntegerField(choices=[(7240, 'Passport'), (7241, 'Documento Nacional de Identidad'), (7242, 'Número de Identificación de Extranjeros'), (0, 'Desconocido')]),
        ),
    ]
