# Generated by Django 2.2.15 on 2020-08-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipanaro', '0009_auto_20180611_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='nid_type',
            field=models.IntegerField(choices=[(7240, 'Passport'), (7241, 'Documento Nacional de Identidad'), (7242, 'Número de Identificación de Extranjeros'), (0, 'Unknown')]),
        ),
    ]
