# Generated by Django 3.1.8 on 2021-05-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipanaro', '0011_auto_20200806_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='date_accepted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='gender_custom',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Agender'), (4, 'Fluid'), (5, 'Non-binary'), (6, 'Pangender'), (7, 'Transgender'), (9, 'Gender non-conforming')]),
        ),
    ]
