# Generated by Django 3.1.8 on 2021-06-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipanaro', '0012_add_membership_fields_20210518_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='address',
            field=models.CharField(max_length=140, verbose_name='Adreça'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='assigned_sex',
            field=models.IntegerField(choices=[(1, 'Home'), (2, 'Dona'), (9, 'No aplicable')], verbose_name='Sexe assignat'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='birthday',
            field=models.DateField(verbose_name='Aniversari'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='city',
            field=models.CharField(max_length=70, verbose_name='Ciutat'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Home'), (2, 'Dona'), (3, 'Agènere'), (4, 'Gènere fluid'), (5, 'Gènere no binari'), (6, 'Pangènere'), (7, 'Transgènere'), (9, 'Gènere no conforme')], verbose_name='Gènere'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='gender_custom',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Gènere a mida'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='nationality',
            field=models.CharField(max_length=20, verbose_name='Nacionalitat'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='nid_type',
            field=models.IntegerField(choices=[(7240, 'Passaport'), (7241, 'DNI'), (7242, 'NIE'), (0, 'Desconegut')]),
        ),
        migrations.AlterField(
            model_name='membership',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telèfon'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telèfon 2'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='Codi Postal'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='province',
            field=models.CharField(max_length=70, verbose_name='Província'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='service',
            field=models.CharField(choices=[('newsletter', 'Butlletí')], max_length=20),
        ),
    ]
