# Generated by Django 3.1.14 on 2024-02-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipanaro', '0013_auto_20210601_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='uid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
