# Generated by Django 3.2 on 2024-02-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipanaro', '0014_auto_20240225_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='id_photo',
            field=models.ImageField(null=True, upload_to='id_photos', verbose_name="Fotografia del document d'identificació"),
        ),
        migrations.AlterField(
            model_name='membership',
            name='city',
            field=models.CharField(max_length=70, verbose_name='Municipi'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='nid',
            field=models.CharField(max_length=50, verbose_name="Número d'identificació"),
        ),
        migrations.AlterField(
            model_name='membership',
            name='nid_type',
            field=models.IntegerField(choices=[(7240, 'Passaport'), (7241, 'DNI'), (7242, 'NIE'), (0, 'Desconegut')], verbose_name="Tipus d'identificació"),
        ),
    ]
