# Generated by Django 3.2.25 on 2024-04-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipanaro', '0016_auto_20240227_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='id_photo2',
            field=models.ImageField(blank=True, help_text="Foto addicional per l'altra banda del document", null=True, upload_to='id_photos', verbose_name="Fotografia addicional del document d'identificació"),
        ),
        migrations.AlterField(
            model_name='membership',
            name='id_photo',
            field=models.ImageField(help_text='Utilitza una foto on es vegin les dues cares del document (max 10Mb), o afegeix una segona foto més avall', null=True, upload_to='id_photos', verbose_name="Fotografia del document d'identificació"),
        ),
    ]
